### ISSUE TITLE
Connection error for downloading .geo.E.tif file

### ISSUE THREAD

**Issue by RoySreeta** [yumorishita/LiCSBAS#303]
Hello Dr. Yumorishita,
I ran the test code for Campi Flegrei from Sept, 2016 to May, 2018 once and the analysis time was 1hr 34 mins. But from then onwards, I have not been able to run the test code with the same frameID and neither with any other frameID because of a connection error occurring. The return is as follows:
Start step: 01
End step:   16
Log file:   log/202310311349batch_LiCSBAS_org_01_16.log

LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py

Frame ID is 124D_04854_171313

Download 124D_04854_171313.geo.E.tif
    ConnectionError for 124D_04854_171313.geo.E.tif in 1th try
    ConnectionError for 124D_04854_171313.geo.E.tif in 2th try
^C

Again for another frameID, the return is the same as follows:
(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas/124D_04854_171313$ cd ../
(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas$ mkdir 039A_05373_131313
(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas$ cd 039A_05373_131313/
(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas/039A_05373_131313$ copy_batch_LiCSBAS.sh

Copy batch_LiCSBAS.sh to the current directory.
(cp -i /home/sreetama/LiCSBAS/batch_LiCSBAS.sh .; chmod 755 batch_LiCSBAS.sh)
Edit batch_LiCSBAS.sh, then run ./batch_LiCSBAS.sh

(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas/039A_05373_131313$ ls
batch_LiCSBAS.sh
(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas/039A_05373_131313$ ./batch_LiCSBAS.sh

Start step: 01
End step:   16
Log file:   log/202310311356batch_LiCSBAS_01_16.log

LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py

Frame ID is 039A_05373_131313

Download 039A_05373_131313.geo.E.tif
    ConnectionError for 039A_05373_131313.geo.E.tif in 1th try
^C

Then I tried accessing this url: http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.U.tif
but it cannot be reached (although I have  a stable wired connection)
I'm not being able to run the test codes. Could you check and let me know if its a server issue or something else or some problem at my end?

**Comment by espiritocz** [comment]
hi.

our processing+data facility is temporarily down for maintenance. This
major maintenance should finish this week.

cheers!

út 31. 10. 2023 v 12:10 odesílatel Yu Morishita ***@***.***>
napsal:

**Comment by AfifJanur** [comment]
Halo,
Has the maintenance been completed or not?,
I've tried downloading on LiCSAR, it seems the result is still the same.
Thank You.

**Comment by RoySreeta** [comment]
The maintenance must be over because I could download this afternoon.

**Comment by MIEMESSI** [comment]
Dear professor, I have encountered such a problem today. Is it the maintenance of the website or the configuration of my network?
LiCSBAS01_get_geotiff.py ver1.6.4 20230215 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20230101 -e 20240101

Frame ID is 143A_05651_131313

Download 143A_05651_131313.geo.E.tif
    ConnectionError for 143A_05651_131313.geo.E.tif in 1th try
    ConnectionError for 143A_05651_131313.geo.E.tif in 2th try
    ConnectionError for 143A_05651_131313.geo.E.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05651_131313/metadata/143A_05651_131313.geo.E.tif
Download 143A_05651_131313.geo.N.tif
    ConnectionError for 143A_05651_131313.geo.N.tif in 1th try
    ConnectionError for 143A_05651_131313.geo.N.tif in 2th try
    ConnectionError for 143A_05651_131313.geo.N.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05651_131313/metadata/143A_05651_131313.geo.N.tif
Download 143A_05651_131313.geo.U.tif
    ConnectionError for 143A_05651_131313.geo.U.tif in 1th try

**Comment by yumorishita** [comment]
Probably it is the maintenance because I cannot download the file either.

**Comment by MIEMESSI** [comment]
Dear @yumorishita sir,

When the LiCS server-side issue can be resolved sir, please let me know sir.

Thank you sir.

**Comment by espiritocz** [comment]
hi. we had some issues indeed.
it works now (just checked)

**Comment by MIEMESSI** [comment]
Dear Professor, I have been unable to download the file again recently. Is it being maintained on the website again?
![image](https://github.com/yumorishita/LiCSBAS/assets/161692921/71d24895-2c6f-4a8c-8fea-5c5a0e7db64a)

**Comment by MIEMESSI** [comment]
Dear professor, I have encountered such a problem one day. Is it the maintenance of the website or the configuration of my network?
LiCSBAS01_get_geotiff.py ver1.6.4 20230215 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20150801 -e 20160801 --get_gacos

Frame ID is 143A_05225_171616

Download 143A_05225_171616.geo.E.tif
    ConnectionError for 143A_05225_171616.geo.E.tif in 1th try
    ConnectionError for 143A_05225_171616.geo.E.tif in 2th try
    ConnectionError for 143A_05225_171616.geo.E.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/143A_05225_171616.geo.E.tif
Download 143A_05225_171616.geo.N.tif
    ConnectionError for 143A_05225_171616.geo.N.tif in 1th try
    ConnectionError for 143A_05225_171616.geo.N.tif in 2th try
    ConnectionError for 143A_05225_171616.geo.N.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/143A_05225_171616.geo.N.tif
Download 143A_05225_171616.geo.U.tif
    ConnectionError for 143A_05225_171616.geo.U.tif in 1th try
    ConnectionError for 143A_05225_171616.geo.U.tif in 2th try
    ConnectionError for 143A_05225_171616.geo.U.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/143A_05225_171616.geo.U.tif
Download 143A_05225_171616.geo.hgt.tif
    ConnectionError for 143A_05225_171616.geo.hgt.tif in 1th try
    ConnectionError for 143A_05225_171616.geo.hgt.tif in 2th try
    ConnectionError for 143A_05225_171616.geo.hgt.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/143A_05225_171616.geo.hgt.tif

Download baselines
    ConnectionError for baselines in 1th try
    ConnectionError for baselines in 2th try
    ConnectionError for baselines in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/baselines
Download network.png
    ConnectionError for network.png in 1th try
    ConnectionError for network.png in 2th try
    ConnectionError for network.png in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/network.png
Download metadata.txt
    ConnectionError for metadata.txt in 1th try
    ConnectionError for metadata.txt in 2th try
    ConnectionError for metadata.txt in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/metadata.txt

Searching latest epoch for mli...
Traceback (most recent call last):
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb9c66c8040>: Failed to establish a new connection: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/epochs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9c66c8040>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 500, in <module>
    sys.exit(main())
  File "/home/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 213, in main
    response = requests.get(url)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/epochs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9c66c8040>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by espiritocz** [comment]
hi.
this was most probably due to maintenance that was performed yesterday.
The website is back on, please try again.

st 5. 6. 2024 v 10:40 odesílatel MIEMESSI ***@***.***> napsal:

**Comment by MIEMESSI** [comment]
Hello, thank you for your reply, but why can't I download it
![image](https://github.com/yumorishita/LiCSBAS/assets/161692921/6d5d3fb9-a032-4332-b6b2-3e3a8f3cf408)

**Comment by espiritocz** [comment]
hi.

the download works for me using any LiCSBAS version, but then it stops
after downloading few tifs, reaching the TooManyRedirects error.
Discussing with support team..



čt 6. 6. 2024 v 3:07 odesílatel MIEMESSI ***@***.***> napsal:

**Comment by yumorishita** [comment]
The bug was fixed in LiCSBAS2 (https://github.com/yumorishita/LiCSBAS2/pull/55). Please use LiCSBAS2 or apply the fix in your local LiCSBAS script.

**Comment by MIEMESSI** [comment]
Dear Professor, I still have a connection error, I don't know what to do
(base) root@LAPTOP-R6PHF274:~# source activate pan
(pan) root@LAPTOP-R6PHF274:~# source  /home/LiCSBAS2/bashrc_LiCSBAS.sh
(pan) root@LAPTOP-R6PHF274:~# cd /home/LiCSBAS2
(pan) root@LAPTOP-R6PHF274:/home/LiCSBAS2# cd 143A_05225_171616
(pan) root@LAPTOP-R6PHF274:/home/LiCSBAS2/143A_05225_171616# ./batch_LiCSBAS.sh

Start step: 01
End step:   16
Log file:   log/202406062240batch_LiCSBAS_01_16.log


LiCSBAS01_get_geotiff.py ver1.6.4 20230215 Y. Morishita
LiCSBAS01_get_geotiff.py -f 143A_05225_171616 -s 20150801 -e 20160801 --get_gacos

Frame ID is 143A_05225_171616

Traceback (most recent call last):
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4b93d65550>: Failed to establish a new connection: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/143A_05225_171616.geo.E.tif (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b93d65550>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 500, in <module>
    sys.exit(main())
  File "/home/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 170, in main
    rc = tools_lib.comp_size_time(url, enutif)
  File "/home/LiCSBAS2/LiCSBAS_lib/LiCSBAS_tools_lib.py", line 78, in comp_size_time
    response = requests.head(file_remote, allow_redirects=True)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/pan/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/143/143A_05225_171616/metadata/143A_05225_171616.geo.E.tif (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b93d65550>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by yumorishita** [comment]
I could not reproduce the error. Please retry.
